# Generated by Django 4.1.7 on 2023-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_name_person_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
