# Generated by Django 4.1.7 on 2023-02-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_note_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_id',
            new_name='author',
        ),
    ]
