# Generated by Django 4.1.7 on 2023-03-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0002_rename_book_keepnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepnote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keepnote',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
